[package]
name = "gito"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
regex = "1.12.2"
reqwest = { version = "0.12", features = ["blocking"] }
dirs = "5.0"

