[package]
name = "gito"
version = "2.0.2"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
regex = "1.12.2"
reqwest = { version = "0.12", features = ["blocking"] }
indicatif = "0.17"
directories = "6.0"
rustyline = "17.0"
